Comment.destroy_all
Story.destroy_all
User.destroy_all
ImportanceMarker.destroy_all
Location.destroy_all
Neighborhood.destroy_all
Category.destroy_all

Neighborhood.create([
  {name: 'Adams Morgan' },
  {name: 'Columbia Heights' },
  {name: 'Howard University' },
  {name: 'Kalorama' },
  {name: 'LeDroit Park' },
  {name: 'Mount Pleasant' },
  {name: 'Park View' },
  {name: 'Pleasant Plains' },
  {name: 'Shaw ' },
  {name: 'Burleith' },
  {name: 'Chinatown' },
  {name: 'Downtown' },
  {name: 'Dupont Circle' },
  {name: 'Federal Triangle' },
  {name: 'Foggy Bottom' },
  {name: 'Georgetown' },
  {name: 'Logan Circle' },
  {name: 'Mount Vernon Square ' },
  {name: 'Penn Quarter' },
  {name: 'Sheridan Kalorama' },
  {name: 'Southwest Federal Center' },
  {name: 'West End' },
  {name: 'American University Park' },
  {name: 'Berkley' },
  {name: 'Cathedral Heights' },
  {name: 'Chevy Chase' },
  {name: 'Cleveland Park' },
  {name: 'Colony Hill' },
  {name: 'Forest Hills' },
  {name: 'Foxhall' },
  {name: 'Friendship Heights' },
  {name: 'Glover Park' },
  {name: 'Kent' },
  {name: 'Massachusetts Heights' },
  {name: 'McLean Gardens' },
  {name: 'North Cleveland Park' },
  {name: 'Observatory Circle' },
  {name: 'Potomac Heights' },
  {name: 'Spring Valley' },
  {name: 'Tenleytown' },
  {name: 'The Palisades' },
  {name: 'Wakefield' },
  {name: 'Wesley Heights' },
  {name: 'Woodland Normanstone' },
  {name: 'Woodley Park ' },
  {name: 'Barnaby Woods' },
  {name: 'Brightwood' },
  {name: 'Brightwood Park' },
  {name: 'Colonial Village' },
  {name: 'Crestwood' },
  {name: 'Fort Totten' },
  {name: 'Hawthorne' },
  {name: 'Manor Park' },
  {name: 'Petworth' },
  {name: 'Queens Chapel' },
  {name: 'Riggs Park' },
  {name: 'Shepherd Park' },
  {name: 'Sixteenth Street Heights' },
  {name: 'Takoma' },
  {name: 'Arboretum' },
  {name: 'Bloomingdale' },
  {name: 'Brentwood' },
  {name: 'Brookland' },
  {name: 'Carver Langston' },
  {name: 'Eckington' },
  {name: 'Edgewood' },
  {name: 'Fort Lincoln' },
  {name: 'Fort Totten' },
  {name: 'Gateway' },
  {name: 'Ivy City' },
  {name: 'Langdon' },
  {name: 'Michigan Park' },
  {name: 'North Michigan Park' },
  {name: 'Pleasant Hill' },
  {name: 'Stronghold' },
  {name: 'Trinidad' },
  {name: 'Truxton Circle' },
  {name: 'Woodridge' },
  {name: 'Barney Circle' },
  {name: 'Capitol Hill' },
  {name: 'Judiciary Square' },
  {name: 'Kingman Park' },
  {name: 'Mount Vernon Triangle' },
  {name: 'Navy Yard' },
  {name: 'Near Northeast' },
  {name: 'NoMa' },
  {name: 'Southwest Waterfront' },
  {name: 'Sursum Corda' },
  {name: 'Swampoodle' },
  {name: 'Benning Heights' },
  {name: 'Benning Ridge' },
  {name: 'Benning' },
  {name: 'Burrville' },
  {name: 'Capitol View' },
  {name: 'Central Northeast' },
  {name: 'Civic Betterment' },
  {name: 'Deanwood' },
  {name: 'Dupont Park' },
  {name: 'Eastland Gardens' },
  {name: 'Fairfax Village' },
  {name: 'Fairlawn' },
  {name: 'Fort Davis' },
  {name: 'Fort Dupont' },
  {name: 'Good Hope' },
  {name: 'Greenway' },
  {name: 'Hillbrook' },
  {name: 'Hillcrest' },
  {name: 'Kenilworth' },
  {name: 'Kingman Park' },
  {name: 'Lincoln Heights' },
  {name: 'Marshall Heights' },
  {name: 'Mayfair' },
  {name: 'Naylor Gardens' },
  {name: 'Penn Branch' },
  {name: 'Randle Highlands' },
  {name: 'River Terrace' },
  {name: 'Skyland' },
  {name: 'Twining' },
  {name: 'Anacostia' },
  {name: 'Barry Farm' },
  {name: 'Bellevue' },
  {name: 'Buena Vista' },
  {name: 'Congress Heights' },
  {name: 'Douglass' },
  {name: 'Fairlawn' },
  {name: 'Garfield Heights' },
  {name: 'Knox Hill' },
  {name: 'Shipley Terrace' },
  {name: 'Washington Highlands' },
  {name: 'Woodland' }
])

Category.create([
  {name: 'Public Interest'},
  {name: 'Politics' },
  {name: 'Business' },
  {name: 'Crime' },
  {name: 'Transportation' },
  {name: 'Entertainment' },
  {name: 'Sports' },
  {name: 'Weather' },
  {name: 'Health' },
  {name: 'Food' },
  {name: 'Tech' },
  {name: 'Education' }
])

#<Location id: 1, name: "Empire State Building", created_at: "2015-04-22 17:59:52", updated_at: "2015-04-22 17:59:52", neighborhood_id: 11, address: nil, latitude: nil, longitude: nil>, #<Location id: 2, name: "The White House", created_at: "2015-04-22 18:56:41", updated_at: "2015-04-22 18:56:41", neighborhood_id: 12, address: "1600 Pennsylvania Avenue Northwest, Washington, DC...", latitude: nil, longitude: nil>, #<Location id: 3, name: "General Assembly Washington DC", created_at: "2015-04-22 18:58:04", updated_at: "2015-04-22 18:58:04", neighborhood_id: 12, address: "1133 15th Street NW, 8th Floor, Washington, DC 200...", latitude: nil, longitude: nil>
Location.create(name: "The White House", neighborhood_id: 12, address: "1600 Pennsylvania Avenue Northwest, Washington, DC 20500", latitude: nil, longitude: nil)
Location.create(
    name: "General Assembly Washington DC",
    neighborhood_id: 12,
    address: "1133 15th Street NW, 8th Floor, Washington, DC 20005",
    latitude: nil,
    longitude: nil)
